### ISSUE TITLE
Feature Request:  Make as Regular JavaScript Version (Sans NPM Requirement)

### ISSUE THREAD

**Issue by maximstewart** [mkslanc/ace-linters#107]
Is there any consideration to make a reglar browser JavaScript version of this than having to have NPPM? I've been trying to use  this without NPM and so far haven't been able to figure out how to set it up as such (if even at all possible). I've also been looking into Browserify to convert this package to single file but am in very early stages of trying that.

**Comment by mkslanc** [comment]
@maximstewart it's already possible by using cdn or any static server. 
- [Example for local/remote static server and inline worker](https://github.com/mkslanc/ace-linters/blob/main/packages/demo/example-fetch-inline-worker.html)
- [Example with using custom cdn service](https://github.com/ajaxorg/ace-samples/tree/master/samples/ace-builds-cdn)
- [Example in Ace Playground](https://mkslanc.github.io/ace-playground/#typescript-language-service)

**Comment by maximstewart** [comment]
Also, then for the first example given I could use AceLanguageClient in place of ServiceManager?

**Comment by maximstewart** [comment]
Okay, I have a working setup that works more or less as needed (using websockets) so closing out ticket. Thank you for your help as that first link cinched it and cleared up some confusion on my part regarding general setup. =) I've attached an image that has my toy structure in place for reference that you can give to others  along with that example link if it might help. Also, thank you for this project! I'm building my own quasi IDE and LSP has been a pain point for me that this looks to have given me a breakthrough. 


![scrshot_2024-03-22 20:17:19](https://github.com/mkslanc/ace-linters/assets/82796688/135e80f9-8dc1-4f8d-81ad-b7c33c4533c7)
