### ISSUE TITLE
Yaml: No schema request service available

### ISSUE THREAD

**Issue by Jxhnn** [mkslanc/ace-linters#115]
Hello ! :).

On the current demo, there is an error on the yaml service (https://mkslanc.github.io/ace-linters/default_services.html).
(No schema request service available)

I tried on my side but I can't make it work !

**Comment by mkslanc** [comment]
@Jxhnn hi! Thank you for your interest in project. Yes, seems API of corresponding services has been changed and schema never sets, I will correct it in next PR
