### ISSUE TITLE
Basic example doesn't even work

### ISSUE THREAD

**Issue by kungfooman** [mkslanc/ace-linters#124]
From `README.md`:

```html
<script src="https://www.unpkg.com/ace-builds@latest/src-noconflict/ace.js"></script>
<script src="https://www.unpkg.com/ace-builds@latest/src-noconflict/ext-language_tools.js"></script>
<script src="https://www.unpkg.com/ace-linters@latest/build/ace-linters.js"></script>
<div id="editor" style="height: 100px">some text</div>

<script>
    ace.require("ace/ext/language_tools"); //To allow autocompletion
    var CssMode = ace.require("ace/mode/css").Mode;
    var editor = ace.edit("editor", {
        enableBasicAutocompletion: true,
        enableLiveAutocompletion: true,
        mode: new CssMode()
    });

    var provider = LanguageProvider.fromCdn("https://www.unpkg.com/ace-linters@latest/build/");
    provider.registerEditor(editor);
</script>
```

Error: `Uncaught TypeError: Cannot read properties of undefined (reading 'Mode')`

![image](https://github.com/mkslanc/ace-linters/assets/5236548/1b9b586f-fe66-4baa-a349-6a5272971f42)

I suggest to kick out TS and use pure ESM with JSDoc, that speeds up your dev cycle and probably preventing bugs like this.

**Comment by mkslanc** [comment]
Right, #125 should make it

**Comment by kungfooman** [comment]
Nice, quick fix, just tested and works :+1: :zap: 

The very first run it logged two warnings about too many event listeners, but 2nd run they were gone :see_no_evil:
