### ISSUE TITLE
while not support lsp textDocument/codeAction ?

### ISSUE THREAD

**Issue by winfredwyw** [mkslanc/ace-linters#127]

**Comment by winfredwyw** [comment]
@mkslanc if you need, i can try become the contributor? i'm using ace, and need ace-linters

**Comment by mkslanc** [comment]
@winfredwyw contributions are always welcome! But as for this one, we are preparing quite big release where `codeactions`, `workspace/edits`,`executeCommand` and other useful stuff, so, please, wait a bit

**Comment by winfredwyw** [comment]
> @winfredwyw contributions are always welcome! But as for this one, we are preparing quite big release where `codeactions`, `workspace/edits`,`executeCommand` and other useful stuff, so, please, wait a bit 随时欢迎贡献！但就这个而言，我们正在准备相当大的版本，其中 `codeactions` 、 `workspace/edits` 、 `executeCommand` 和其他有用的东西，所以，请稍等一下

Cool, Welcome contact me anytime

**Comment by mkslanc** [comment]
@winfredwyw new release should allow all that stuff - [Release notes v1.3.0](https://github.com/mkslanc/ace-linters/releases/tag/v1.3.0)
