### ISSUE TITLE
Add example for custom JSON schema's

### ISSUE THREAD

**Issue by whazor** [mkslanc/ace-linters#131]
As custom JSON is a popular request for ACE, please provide an example how to add a JSON Schema Service to ace-linters.

See:
- https://github.com/ajaxorg/ace/issues/2883
- https://github.com/ajaxorg/ace/issues/3885

**Comment by mkslanc** [comment]
@whazor hey! [This wiki page](https://github.com/mkslanc/ace-linters/wiki/Configuring-Ace-linters-with-JSON-language-service) should make it
