### ISSUE TITLE
`return` without `function` syntax

### ISSUE THREAD

**Issue by superdinmc** [mkslanc/ace-linters#134]
~I am trying to load TypeScript types from `/req.d.ts`, without using websocket to run the linter.
It's just a simple types that contain the following:~
```ts
class CSRequest extends Request {
  constructor() {
    super();
  }
  query: Record<string, string>
  params: Record<string, string>
}
declare var req: CSRequest;
```
~I fixed it the types, but it seems that ESLint is saying `req` is not defined.~ I fixed it

Moreover, I have a code that gets parsed using `new Function(...)`(I know it's unsafe but the editor is authenticated), the linter throws `A "return" statement can only be used within a function.` for the following code:
```js
// Test code to echo all query parameters
return new Response(JSON.stringify(req.query), {
    headers: {
        'Content-Type': 'application/json'
    }
});
```

**Comment by mkslanc** [comment]
@superdinmc could you show more detailed snippet? Or is it the whole code on top-level of file?

**Comment by superdinmc** [comment]
That is the entire file

**Comment by superdinmc** [comment]
That is the entire file
My current workaround is to use `errorCodesToTreatAsInfo`, but I don't think that's the proper way
I also want to force the return type to be a Response`.

**Comment by mkslanc** [comment]
@superdinmc Sorry, for late response, as I see you have few options:
1. Continue usage of `errorCodesToTreatAsInfo` or even `errorMessagesToIgnore` 
2. Wrap it to anonymous function
```javascript
(() => {
    // Test code to echo all query parameters
    return new Response(JSON.stringify(req.query), {
        headers: {
            'Content-Type': 'application/json'
        }
    });
})();
``` 
to satisfy linter (seems a bit overkill for me)
3. If your context allows, you could refactor the code to avoid the use of return:
```javascript
const response = new Response(JSON.stringify(req.query), {
    headers: {
        'Content-Type': 'application/json'
    }
});
response; // The result that your execution context will return
```
