### ISSUE TITLE
Examples on demo site are broken (services) ?

### ISSUE THREAD

**Issue by JLTs66** [mkslanc/ace-linters#135]
Examples on demo site are broken ?
https://mkslanc.github.io/ace-linters/default_services.html  : only some mode work
https://mkslanc.github.io/ace-linters/change_mode.html : idem (contents don't change)

On my side, on a webpage with a simple ace editor with ace-linters, this modes php, html, js and css, do nothing more that just ace without ace-linters.  (like your demos)
Ace-linter 1.3.0
Ace : 1.36.2

**Comment by JLTs66** [comment]
Note, on my webpage, I just tried php, html, js and css; I stopped after see that your code don't work. The xxx_service.js seem to be never loader by your service provide (I copied the https://github.com/mkslanc/ace-linters/blob/main/packages/demo/webworker-lsp/webworker.ts) et link with the good URL).

**Comment by mkslanc** [comment]
@JLTs66 hey! It just need some time for first init, especially for page with a lot of linters.
![image](https://github.com/user-attachments/assets/69ac9589-5e05-4121-81b7-7aca4d88f0a5)

**Comment by JLTs66** [comment]
https://mkslanc.github.io/ace-linters/default_services.html

I'm waiting 10 minutes; it's enough ?
json not work, css not work, PHP detect no error/suggestion in : 
```
function nfact($n) : integer {
    echo $toto;
    if ($n == 0) {
        return "toto";
        
                                                        }
    			else {
        return "tata";
    }
}
```

Need more examples ?

**Comment by mkslanc** [comment]
Are there any errors in the console? The PHP service uses the same library as Ace, but it was kept only for backward compatibility with Ace’s workers (it’s outdated and doesn’t show errors in Ace either). JSON and CSS should work. If the examples here aren’t working for some reason, you can check out a real use case in the [Ace Playground](https://mkslanc.github.io/ace-playground/#hello-world).
