### ISSUE TITLE
Tooltip sometimes not showing on hover of text underlined

### ISSUE THREAD

**Issue by Jxhnn** [mkslanc/ace-linters#137]
## Tooltip not showing on underlined error in some cases

**Describe the bug**

There seems to be an issue where the error tooltip does not appear when hovering over underlined text in certain situations. It's unclear what specific conditions trigger this problem.

**To reproduce**

1. Go to https://mkslanc.github.io/ace-linters/default_services.html
2. Hover over the underlined word "os" in the Python code example. No tooltip appears.
3. Similarly, go to https://mkslanc.github.io/ace-linters/webworker.html
4. Hover over the underlined word "country". Again, no tooltip is displayed.

**Expected behavior**

Hovering over underlined text that indicates an error should consistently display a tooltip explaining the error / info / warning.

**Comment by mkslanc** [comment]
@Jxhnn hey! Should be fixed in [new version](https://github.com/mkslanc/ace-linters/releases/tag/v1.3.1)
