### ISSUE TITLE
Missing manager definition in the Wiki page for Configuring Ace linters with JSON language service

### ISSUE THREAD

**Issue by craigvantonder** [mkslanc/ace-linters#142]
The wiki documentation on [setting up the web worker](https://github.com/mkslanc/ace-linters/wiki/Configuring-Ace-linters-with-JSON-language-service#setting-up-the-web-worker) when configuring the JSON language service is missing a key detail, the "manager" definition:

```
import {ServiceManager} from "ace-linters/build/service-manager";

// Instantiate the service manager instance?
let manager = new ServiceManager(self); <-------------- HERE

// Register the JSON service
manager.registerService("json", {
    module: () => import("ace-linters/build/json-service"),
    className: "JsonService",
    modes: "json",
});

// Register the JSON5 service
manager.registerService("json5", {
    module: () => import("ace-linters/build/json-service"),
    className: "JsonService",
    modes: "json5",
});
```

As is defined in the [first example of the readme](https://github.com/mkslanc/ace-linters#example-client-with-pre-defined-services) or more specifically [within the webworker-lsp example](https://github.com/mkslanc/ace-linters/blob/main/packages/demo/webworker-lsp/webworker.ts).

Anyhow, this is really cool. Thank you for all of the effort!

**Comment by mkslanc** [comment]
@craigvantonder thank you! you are right, seems I missed it while creating guide -> corrected in new revision
