### ISSUE TITLE
WASM based formatters

### ISSUE THREAD

**Issue by mkslanc** [mkslanc/ace-linters#145]
I have one offtopic question but related to this project:
There few wasm based formatter available for languages like lua, clang, zig, go, etc.
So it is good to integrate those things directly in ace-linters or through extensions.

Second thing is python ruff linter got some updates, as now it supports formatter etc(so good to update it)

_Originally posted by @bajrangCoder in https://github.com/mkslanc/ace-linters/issues/144#issuecomment-2547451260_

**Comment by bajrangCoder** [comment]
Here is one of them : [Formatters](https://github.com/wasm-fmt)

**Comment by bajrangCoder** [comment]
Nice 👍
