### ISSUE TITLE
Unusable through websocket

### ISSUE THREAD

**Issue by bajrangCoder** [mkslanc/ace-linters#83]
I have tried both mode of ace-linter and 
According to me , ace-linter is not practically usable through websocket , here are problems:

- A lots of error in the console(but it work and provide LSP) which makes it laggy
- in some case it's completions are not visible in autocompletion box (mainly in svelte mode while typing any html element)
- and many LSP servers are not compatible yet with ace-linters such as rust-analyzer

> **Note**
> These errors are faced in case of multiple languages(like python, svelte) and through webworker there is no any complain and it works smoothly

**Comment by mkslanc** [comment]
Hi @bajrangCoder ! Could you provide examples in such format: ls server - error screenshot? I will try to fix it in short time.

**Comment by bajrangCoder** [comment]
Here are some screenshots:

![Screenshot_20231020-214039~2](https://github.com/mkslanc/ace-linters/assets/71929976/68cba0c0-b753-41f8-ac17-fe6a341a48ac)
![Screenshot_20231020-214007~2](https://github.com/mkslanc/ace-linters/assets/71929976/bfd868d0-106c-48bf-9a93-f587b7d92fce)

And there are also long warnings and errors on server but it seems that doesn't intrupt the program.

And also ace-linter isn't compatible with LSP servers , today I have tried [astro language server](https://github.com/withastro/language-tools/tree/main/packages/language-server) , which fails and crashed the server...

**Comment by mkslanc** [comment]
Which server it is ?

**Comment by bajrangCoder** [comment]
First screenshot is of svelte and second one of python
And using your websocket-ls as server

**Comment by mkslanc** [comment]
@bajrangCoder new version of ace-linters and https://github.com/mkslanc/websockets-ls should make it better. I solved some minor problems in client itself. Right now bridge would swallow errors without sending it to client, which is not good, but that's the only what I could suggest for now. 

Meanwhile I started working on heavy refactoring of language client part (provider would support multiple servers like it's doing for services), but it could take some time.

**Comment by bajrangCoder** [comment]
> @bajrangCoder new version of ace-linters and https://github.com/mkslanc/websockets-ls should make it better. I solved some minor problems in client itself. Right now bridge would swallow errors without sending it to client, which is not good, but that's the only what I could suggest for now.
> 

Yeah , now it's much better and wonderful experience in pythononly , but in case of svelte it still returns a lot of error like undefined file name, $somehandler , etc.....

> Meanwhile I started working on heavy refactoring of language client part (provider would support multiple servers like it's doing for services), but it could take some time.

Wow , sounds great 😃

**Comment by mkslanc** [comment]
@bajrangCoder new version should allow all that including mixing with default services. I also added [use case diagram](https://github.com/mkslanc/ace-linters/wiki/Usage-Scenarios-Overview) to point to specific scenario. [New version of server bridge](https://github.com/mkslanc/websockets-ls) should handle python, astro, svelte and go. Also you could add your different socket servers with new `registerServer` endpoint on web-worker side or directly through `AceLanguageClient` on main thread. More information [here](https://github.com/mkslanc/ace-linters?tab=readme-ov-file#new-features-in-100) . I hope that's what you expected from that update :) Feel free to drop any found bugs.

**Comment by bajrangCoder** [comment]
**wow**, let try..

**Comment by bajrangCoder** [comment]
Still gopls and rust-analyzer doesn't works, I guess it's because they need the workspace uri 🤔

**Comment by mkslanc** [comment]
@bajrangCoder gopls needs some configuration from server side, or some meta files corresponding to go file. I am not go developer, so I actually don't know what to provide there. Also it seems out of scope here - it's not client's problem, it's more like bridge problem, which could be solved as separate package like it has been done for monaco (for example)

**Comment by bajrangCoder** [comment]
Ok
