### ISSUE TITLE
ace-linters\build\python-service Webworker forces us to have unsafe-wasm-eval in our CSP, thus worsening security

### ISSUE THREAD

**Issue by PetreStegaroiu** [mkslanc/ace-linters#86]
In order to use your handy python web-worker, we have to update our CSP (Content Security Policy) to have script-src 'wasm-unsafe-eval' which akes us more vulnerable from security POV.
This is because the ace-linters\build\python-service.js file exports a huge hard-coded wasm (See screenshot below)

![image](https://github.com/mkslanc/ace-linters/assets/92522455/784f943b-12f3-441a-bdd3-aa0e24c291a9)

I believe the code above is generated from _'input = fetch(input)'_ from https://github.com/mkslanc/ace-linters/blob/fb567a00237542b1c3f13efa90776b2d76f88f98/packages/ace-linters/src/services/python/pkg/ruff_wasm.js#L598 

Without the "wasm-unsafe-eval" add-on to our CSP, we get this error:
![image](https://github.com/mkslanc/ace-linters/assets/92522455/7012e3b0-44a9-4c0d-9643-ae2b40c614fc)

**python-service.js:2  Uncaught (in promise) CompileError: WebAssembly.instantiateStreaming(): Refused to compile or instantiate WebAssembly module because 'unsafe-eval' is not an allowed source of script** in the following Content Security Policy directive: "script-src....

Is there any chance you can update the code  for the python web worker not to use wasm. i notice that the lua web-worker does not use it.
Or maybe, do you have an alternative solution to worsening our CSP?

**Comment by mkslanc** [comment]
@PetreStegaroiu, Unfortunately I don't know many reliable python linters except native ones (which needs WASM to work). If you know some on TS/JS, please bring them here so I could wrap them as alternative services. As alternative you could use this lib as language client with pylsp like in [this example](https://github.com/mkslanc/ace-linters/blob/main/packages/demo/websockets-pylsp/client.ts) (it would work through websockets though, not webworkers). Also you could try to use CSP Nonce directive for this linter itself, but here I couldn't help you a lot, cause it's not my area of expertise :)

**Comment by PetreStegaroiu** [comment]
Thank you for your quick feedback mkslanc! 
I wish I knew a reliable TS/JS python linter, as just hoping you maybe had one that you were planning to replace the current one.

Websocket solution has its own complications, but we might have to consider it.

We have cspNonce directive, but it also needs the wasm-unsafe-eval for the linter to function. 

We will make this python linter work either by keeping the CSP policy above or using websockets.
Thank you once again for letting us know the situation! :)
