### ISSUE TITLE
Request for SQL language features

### ISSUE THREAD

**Issue by marinsokol5** [mkslanc/ace-linters#88]
In Ace, a customer opened an issue to ask for SQL auto-complete functionality in Ace, and we can try to consider the SQL language server here. 
Reference: https://github.com/ajaxorg/ace/issues/5421

**Comment by mkslanc** [comment]
Hey, @marinsokol5 . Thanks for the suggestion about SQL auto-complete in ace-linters. I'm diving into the research to explore the possibilities of integrating a SQL language server. I'll update you as I uncover more.

**Comment by mkslanc** [comment]
@marinsokol5 @melin I've decided to publish all SQL linters as separate [npm module](https://www.npmjs.com/package/ace-sql-linter) . You could easily add those to `ace-linters` by installing package and [registering it on web workers side](https://github.com/mkslanc/ace-linters/blob/v1.0.1/packages/demo/webworker-lsp/webworker.ts#L114)
