### ISSUE TITLE
Incorrect sync mode in language client

### ISSUE THREAD

**Issue by fshauge** [mkslanc/ace-linters#96]
It seems that the language client sends incremental changes when the server's capability is set to `TextDocumentSyncKind.Full`, and full changes when the server's capability is set to `TextDocumentSyncKind.Incremental`. I guess [this boolean expression](https://github.com/mkslanc/ace-linters/blob/bd37a81895de2e73d4bc784064b8e9e0fe32483e/packages/ace-linters/src/services/language-client.ts#L264) should be inverted.

<img width="1512" alt="image" src="https://github.com/mkslanc/ace-linters/assets/1189327/ea2bc900-70f3-4b39-ab66-74fb6baf8a92">

As you can see from the `Watch` panel, the server has responded with the `TextDocumentSyncKind.Incremental` capability, but the function `setValue` is still called.

**Comment by mkslanc** [comment]
@fshauge thank you for your interest in this project! It's indeed bug and should be fixed in #98 and will be included to next release
